### ISSUE TITLE
Attempted code presenting with MD --> potential to include contents?

### ISSUE THREAD

**Issue by jangari** [gitpitch/code-presenting#1]
I was just having a crack at a code slide, by using the PITCHME.md code itself. Probably not the wisest choice in testing, but it had a bizarre effect: the contents of the referred file was inserted into the position where I had attempted to pull in the code in a window.

This raises an interesting question, and one that I had in mind some time ago: Is it possible to include the MD contents of other files in a gitpitch presentation? If so, then this would greatly help in maintaining multiple presentations that rely on the same content. Update that content once...

Interested to hear your thoughts

**Comment by gitpitch** [comment]
hi @jangari thanks for getting in touch. To your specific question, have you had a chance to check out GitPitch's support for [modular markdown](https://github.com/gitpitch/gitpitch/wiki/Modular-Markdown)?

This feature is designed to let your build presentations in a modular way, using a series of markdown files that can be easily combined in any order to create the content of one or indeed many presentations. This supports re-use, shared content, etc across presentations. Giving you your desired _modify-once-see-changes-everywhere_ behavior. The wiki page I linked to above gives more detail.

I also recommend reading the [shared assets](https://github.com/gitpitch/gitpitch/wiki/Asset-Sharing) section of the [Single Repo - Multiple Presentation](https://github.com/gitpitch/gitpitch/wiki/Asset-Sharing) wiki page as it compliments the modular markdown approach.

I'd be interested in your feedback once you've had a chance to look this over. Thanks.

**Comment by jangari** [comment]
Ugh, this is great! I don't know why I didn't see it earlier!!

Thanks for this fantastic platform! I'll comment here if I have any queries.

**Comment by jangari** [comment]
Hi again, 

Is it possible to include md files from other github repositories? I'm now automatically generating some stats to include in presentations, and they're being uploaded to another repository.

**Comment by gitpitch** [comment]
Hi @jangari, it's not possible. All markdown for a given presentation must be found in the repo for that presentation. Not sure what format your stats are held (raw data, charts, images etc) but if you want to share non-markdown content (such as images, screenshots, etc) you can host those at any public hosted location (such as your GitHub pages) and then reference those by absolute URL in your presentation markdown.

**Comment by jangari** [comment]
Didn't think so. No worries.

I have a pitch that refers to stats, i.e., how many researchers we have trained, in how many courses, at how many locations, which is stored as md in another repository. The reason for the different repository is that the stats are generated by a separate system that hosts our training database (and outputs a small md file from some simple psql queries) and I didn't want to clone the repository that holds our training material *into* the database repository, nor did I want to overburden that server with another, somewhat heavy git repo with lots of binary objects. I was also looking into the possibility of pushing a single file into a repo without having to clone the entire thing, and also submodules looks like it could be relevant here. 

The best solution would be to remotely connect to the psql database from a server that held the gitpitch repository and run the queries from that, outputting the md file locally. I don't know why I didn't think of this earlier!

**Comment by jangari** [comment]
Anyway, my earlier issue is well and truly closed. Thanks again!

**Comment by jangari** [comment]
It appears that ---?include can only go one level deep; an included markdown file cannot itself include another asset. 

Am I right in that?

**Comment by gitpitch** [comment]
That is correct. Only your top-level `PITCHME.md` can include another markdown file. This keeps things simple, which helps to prevent things like circular dependencies etc.
